version: "3"

services:

    webapp:
        image: ithings-webapp:1.0.0
        ports: 
            - 8000:80
    
    api:
        image: ithings-api:1.0.0
        expose:
            - 8082:8082        
    
    mysql:
        image: mysql
        ports:
        - 3306:3306        