version: "3"

services:

    webapp:
        image: adybunny2326/ithings-webapp:1.0.0
        ports: 
            - 8004:80
    
    api:
        image: adybunny2326/ithings-api:1.0.0
        ports:
            - 8082:8082       
    
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "orbit"
            MYSQL_DATABASE: "orbit"
            MYSQL_USER: "orbit"
            MYSQL_PASSWORD: "orbit"