version: "3"

services:

    webapp:
        image: ithings-webapp:1.0.0
        ports: 
            - 8000:80
    
    api:
        image: ithings-api:1.0.0
        expose:
            - 8082:8082        
    
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "orbit"
            MYSQL_DATABASE: "orbit"
            MYSQL_USER: "orbit"
            MYSQL_PASSWORD: "orbit"